const C2S = {
  JOIN_ROOM:     'JOIN_ROOM',
  PLAYER_UPDATE: 'PLAYER_UPDATE',
  BOSS_KILL:     'BOSS_KILL',
  GAME_OVER:     'GAME_OVER',
  RANKING_REQ:   'RANKING_REQ',
};

const S2C = {
  ROOM_JOINED:   'ROOM_JOINED',
  PLAYER_JOINED: 'PLAYER_JOINED',
  PLAYER_LEFT:   'PLAYER_LEFT',
  PLAYERS_STATE: 'PLAYERS_STATE',
  RANKING_RES:   'RANKING_RES',
  GAME_OVER_ACK: 'GAME_OVER_ACK',
};

module.exports = { C2S, S2C };
